name: flutter_swiper
description: The best swiper(carousel) for flutter, with multiple layouts, infinite loop. Compatible with Android & iOS.
version: 1.1.6
author: JZoom <jzoom8112@gmail.com>
homepage: https://github.com/jzoom/flutter_swiper

dependencies:
  flutter:
    sdk: flutter

  transformer_page_view:
    git:
      url: git@github.com:tmcmaster/transformer_page_view.git
  flutter_page_indicator:
    git:
      url: git@github.com:tmcmaster/flutter_page_indicator.git

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=3.29.2'

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  flutter_page_indicator:
    path: ../flutter_page_indicator
  transformer_page_view:
    path: ../transformer_page_view
